language: java

jdk:
  - openjdk8
  - openjdk11

addons:
  sonarcloud:
    organization: "mc1arke-github"
    token:
      secure: MZKJ5EKXJg5fiOSTJY0eaUxfhaLFsODIOLXzz62Ix3fVHhC4vpzJoWedkB5JWjKKx3LDpVacqJvfjYxxA3QpYg11rt50ETC7xAIityTQ0YD1GfQcATwEKPU3axcqROjezbe12xUqP2rjahd8cPFPluyRP4zcf+iZpgSmX0g9hv7FOB905zJ0GwJhirDN5jnGIlOQQzxBimXDR3NUWxBQzmnUP0YwOCO7SH+Q9TxcHfg9GmtCQWiV3AtrNeyWrnDBuxL98WKA156x+vMRa8VT/AbJ3rBeJ/3kPkfeHmEgFyHwC68ESCemy88tdEd+LJpOxj05945mKz3+CKHq1bmkpjepe9Jl/TRTaHHy9aMJifutq2dYgqGRbNQqi+QGSLnhSJDfoGj251w7suf3t2L/ceD3Z6hB3P0uJF57n8WAo/crGIZ/5F4ia0wwXdyWQEM7vS6vAdSFvh16vVp+VkbGC9pXO5mO1mP8Hm5svR0DuBJhtXygPzqgGNRuYvC3ekzPAMpg0PGPuhjVm2DAbIvegVQz4Yt+Bk/4fHCNZ7QEH1J3vFYfANBTCoulHwGq09IkJj5ujOKv3RTK55e8g/0l4hTJ5lPSDWBN/RFsT+boDhxcTmgPbOSg0kFWpUuvoeJBMe9Mo+PCE4or3+P2z6jhpx5hshj69/d62HjTl0MHKWI=

script:
  - ./gradlew sonarqube -Dsonar.projectKey=mc1arke_sonarqube-community-branch-plugin
